### ISSUE TITLE
Order of rules don't save after postprocessing

### ISSUE THREAD

**Issue by fliptheweb** [jo-asakura/postcss-neat#20]
I have `float: none;` in my selector, cuz i dont need clearfix and have just one column.
```css
.grid__content {
  @neat-span-columns 8;
  @neat-shift 2;
  float: none;
}
```
But after `postcss-neat` we`ll have:
```css
.grid__content {
  float: none;
  display: block;
  float: left;
  margin-right: 2.35765160%;
  width: 65.88078280%;
  margin-left: 17.05960860%; 
}
```
